name: Install

on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.7", "3.10"]
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Create wheel and tar.gz
        run: |
          make package
      - name: Install package
        run: |
          python -m pip install unpacked/.
      - name: Test import and simple usage
          python -c "import isodata;print(isodata.__version__)"
          python -c "import isodata;isodata.list_isos()"
